name: jonathanlittlewood
favicon: null
layout_spectrum: 0.01201867125928402
typography_spectrum: 0.568888912210241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1142170128878206
  lightness: 0.15515260212123394
  saturation: 0.11278048576787114
  rhythmicContrast: 0.8303569299168885
purpose: []
